spring:
  profiles:
    active:
    - dev
---                 
  server:
    port: 8003
    
  logging:
    level:
      com.jisheng.dao: debug
    
  mybatis:
    config-location: classpath:mybatis/mybatisconf.xml
    type-aliases-package: com.jisheng.pojo
    mapper-locations:
    - classpath:mybatis/mapper/*.xml
  
  spring:
    application:
     name: springCloudProvider
    datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
     username: scott
     password: jisheng
#    jackson:
#      serialization:
#        fail-on-empty-beans: false
        
  eureka:
    client:
      service-url:
       defaultZone: http://localhost:7001/eureka/ #eureka服务中心的地址
    instance:
      prefer-ip-address: true                     #优先显示ip
#配置点击之后的项目info信息
  info:
   app.name: atguigu-microservicecloud
   company.name: www.atguigu.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
      
     
     
     
   
 